In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
### Vocabulary size
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1059, 5616, 5430, 6514], [1059, 5616, 5430, 7406], [1059, 6754, 5430, 5328], [895, 4145, 1315, 9455, 111], [895, 4145, 1315, 9455, 6831], [8540, 1059, 5315, 5430, 6284], [3512, 1343, 6036, 9455]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1059 5616 5430 6514]
 [   0    0    0    0 1059 5616 5430 7406]
 [   0    0    0    0 1059 6754 5430 5328]
 [   0    0    0  895 4145 1315 9455  111]
 [   0    0    0  895 4145 1315 9455 6831]
 [   0    0    0 8540 1059 5315 5430 6284]
 [   0    0    0    0 3512 1343 6036 9455]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [13]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

[[[ 1.99665874e-03  3.97014283e-02 -2.15719230e-02  1.30890943e-02
    1.14156008e-02  2.66069435e-02  4.82051708e-02  4.08397205e-02
    7.61455297e-03 -2.89482716e-02]
  [ 1.99665874e-03  3.97014283e-02 -2.15719230e-02  1.30890943e-02
    1.14156008e-02  2.66069435e-02  4.82051708e-02  4.08397205e-02
    7.61455297e-03 -2.89482716e-02]
  [ 1.99665874e-03  3.97014283e-02 -2.15719230e-02  1.30890943e-02
    1.14156008e-02  2.66069435e-02  4.82051708e-02  4.08397205e-02
    7.61455297e-03 -2.89482716e-02]
  [ 1.99665874e-03  3.97014283e-02 -2.15719230e-02  1.30890943e-02
    1.14156008e-02  2.66069435e-02  4.82051708e-02  4.08397205e-02
    7.61455297e-03 -2.89482716e-02]
  [ 9.33250040e-03 -2.76572239e-02  2.48679183e-02  1.31315924e-02
   -7.03915209e-03  3.40435989e-02  2.74782293e-02 -3.44303139e-02
   -3.59287858e-02 -4.56974767e-02]
  [-4.53862809e-02 -7.74073601e-03 -1.64579526e-02 -1.50955804e-02
    1.78090371e-02  3.03531922e-02 -2.54551657e-02 -1.05170012e-02
    1.20811835e-